on:
  push:
    tags:
    - "*"
    
env:
  PROJECT_NAME: dotPeekser.SC.Solr.ManagedSchema
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  PROJECT_PATH: ""
  NUPKGS_FOLDER: ""
  
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set env variable PROJECT_PATH
      run: echo "PROJECT_PATH=$env:GITHUB_WORKSPACE\src\$env:PROJECT_NAME\$env:PROJECT_NAME.csproj" >> $env:GITHUB_ENV
    
    - name: Set env variable NUPKGS_FOLDER
      run: echo "NUPKGS_FOLDER=$env:GITHUB_WORKSPACE\nupkgs" >> $env:GITHUB_ENV
      
    - name: Set PACKAGE_VERSION
      run: echo "PACKAGE_VERSION=${{ github.ref_name }}" >> $env:GITHUB_ENV
      
    - name: Version information
      run: echo "Tag name from PACKAGE_VERSION - $env:PACKAGE_VERSION"
      
    - name: Build
      run: dotnet build --configuration Release /p:Version=$env:PACKAGE_VERSION
      
    - name: Test
      run: dotnet test --configuration Release /p:Version=$env:PACKAGE_VERSION --no-build
      
    - name: Pack
      run: dotnet pack "$env:PROJECT_PATH" --configuration Release /p:Version=$env:PACKAGE_VERSION --no-build --output "$env:NUPKGS_FOLDER"
    
    - name: Push
      run: dotnet nuget push "$env:NUPKGS_FOLDER\dotPeekser.SC.Solr.ManagedSchema.$env:PACKAGE_VERSION.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${env:NUGET_TOKEN}
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
