on:
  push:
    tags:
    - "*"
    
env:
  PROJECT_NAME: dotPeekser.SC.Solr.ManagedSchema
  PROJECT_PATH: ${GITHUB_WORKSPACE}\src\$PROJECT_NAME\$PROJECT_NAME.csproj
  NUPKGS_FOLDER: ${GITHUB_WORKSPACE}\nupkgs
  
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set PACKAGE_VERSION
      run: echo "PACKAGE_VERSION=${{ github.ref_name }}" >> $env:GITHUB_ENV
      
    - name: Version information
      run: echo "Tag name from PACKAGE_VERSION - $env:PACKAGE_VERSION"
      
    - name: Build
      run: dotnet build --configuration Release /p:Version=$VERSION
      
    - name: Test
      run: dotnet test --configuration Release /p:Version=$VERSION --no-build
      
    - name: Pack
      run: dotnet pack "$PROJECT_PATH" --configuration Release /p:Version=$VERSION --no-build --output "$NUPKGS_FOLDER"
