on:
  push:
    tags:
    - "*"
    
env:
  PROJECT_NAME: dotPeekser.SC.Solr.ManagedSchema
  PROJECT_PATH: ${GITHUB_WORKSPACE}\src\$PROJECT_NAME\$PROJECT_NAME.csproj
  NUPKGS_FOLDER: ${GITHUB_WORKSPACE}\nupkgs
  
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set PACKAGE_VERSION
      run: echo "PACKAGE_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
    - name: Test
      run: echo $PACKAGE_VERSION
      
    - name: Version information
      run: echo "Tag name from PACKAGE_VERSION - $PACKAGE_VERSION"
